// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideoRentalStore.DataAccess;

#nullable disable

namespace VideoRentalStore.DataAccess.Migrations
{
    [DbContext(typeof(VideoRentalDbContext))]
    partial class VideoRentalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VideoRentalStore.Domain.Entities.Cast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("Casts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MovieId = 1,
                            Name = "Keanu Reeves",
                            Role = 0
                        },
                        new
                        {
                            Id = 2,
                            MovieId = 1,
                            Name = "Laurence Fishburne",
                            Role = 0
                        },
                        new
                        {
                            Id = 3,
                            MovieId = 1,
                            Name = "Carrie-Anne Moss",
                            Role = 0
                        },
                        new
                        {
                            Id = 4,
                            MovieId = 1,
                            Name = "Lana Wachowski",
                            Role = 1
                        },
                        new
                        {
                            Id = 5,
                            MovieId = 1,
                            Name = "Joel Silver",
                            Role = 2
                        },
                        new
                        {
                            Id = 6,
                            MovieId = 2,
                            Name = "Leonardo DiCaprio",
                            Role = 0
                        },
                        new
                        {
                            Id = 7,
                            MovieId = 2,
                            Name = "Joseph Gordon-Levitt",
                            Role = 0
                        },
                        new
                        {
                            Id = 8,
                            MovieId = 2,
                            Name = "Elliot Page",
                            Role = 0
                        },
                        new
                        {
                            Id = 9,
                            MovieId = 2,
                            Name = "Christopher Nolan",
                            Role = 1
                        },
                        new
                        {
                            Id = 10,
                            MovieId = 2,
                            Name = "Emma Thomas",
                            Role = 2
                        },
                        new
                        {
                            Id = 11,
                            MovieId = 3,
                            Name = "Leonardo DiCaprio",
                            Role = 0
                        },
                        new
                        {
                            Id = 12,
                            MovieId = 3,
                            Name = "Kate Winslet",
                            Role = 0
                        },
                        new
                        {
                            Id = 13,
                            MovieId = 3,
                            Name = "Billy Zane",
                            Role = 0
                        },
                        new
                        {
                            Id = 14,
                            MovieId = 3,
                            Name = "James Cameron",
                            Role = 1
                        },
                        new
                        {
                            Id = 15,
                            MovieId = 3,
                            Name = "Jon Landau",
                            Role = 2
                        },
                        new
                        {
                            Id = 16,
                            MovieId = 4,
                            Name = "Marlon Brando",
                            Role = 0
                        },
                        new
                        {
                            Id = 17,
                            MovieId = 4,
                            Name = "Al Pacino",
                            Role = 0
                        },
                        new
                        {
                            Id = 18,
                            MovieId = 4,
                            Name = "James Caan",
                            Role = 0
                        },
                        new
                        {
                            Id = 19,
                            MovieId = 4,
                            Name = "Francis Ford Coppola",
                            Role = 1
                        },
                        new
                        {
                            Id = 20,
                            MovieId = 4,
                            Name = "Albert S. Ruddy",
                            Role = 2
                        },
                        new
                        {
                            Id = 21,
                            MovieId = 5,
                            Name = "Matthew McConaughey",
                            Role = 0
                        },
                        new
                        {
                            Id = 22,
                            MovieId = 5,
                            Name = "Anne Hathaway",
                            Role = 0
                        },
                        new
                        {
                            Id = 23,
                            MovieId = 5,
                            Name = "Jessica Chastain",
                            Role = 0
                        },
                        new
                        {
                            Id = 24,
                            MovieId = 5,
                            Name = "Christopher Nolan",
                            Role = 1
                        },
                        new
                        {
                            Id = 25,
                            MovieId = 5,
                            Name = "Emma Thomas",
                            Role = 2
                        },
                        new
                        {
                            Id = 26,
                            MovieId = 6,
                            Name = "Christian Bale",
                            Role = 0
                        },
                        new
                        {
                            Id = 27,
                            MovieId = 6,
                            Name = "Heath Ledger",
                            Role = 0
                        },
                        new
                        {
                            Id = 28,
                            MovieId = 6,
                            Name = "Aaron Eckhart",
                            Role = 0
                        },
                        new
                        {
                            Id = 29,
                            MovieId = 6,
                            Name = "Christopher Nolan",
                            Role = 1
                        },
                        new
                        {
                            Id = 30,
                            MovieId = 6,
                            Name = "Charles Roven",
                            Role = 2
                        },
                        new
                        {
                            Id = 31,
                            MovieId = 7,
                            Name = "John Travolta",
                            Role = 0
                        },
                        new
                        {
                            Id = 32,
                            MovieId = 7,
                            Name = "Samuel L. Jackson",
                            Role = 0
                        },
                        new
                        {
                            Id = 33,
                            MovieId = 7,
                            Name = "Uma Thurman",
                            Role = 0
                        },
                        new
                        {
                            Id = 34,
                            MovieId = 7,
                            Name = "Quentin Tarantino",
                            Role = 1
                        },
                        new
                        {
                            Id = 35,
                            MovieId = 7,
                            Name = "Lawrence Bender",
                            Role = 2
                        },
                        new
                        {
                            Id = 36,
                            MovieId = 8,
                            Name = "Robert Downey Jr.",
                            Role = 0
                        },
                        new
                        {
                            Id = 37,
                            MovieId = 8,
                            Name = "Chris Evans",
                            Role = 0
                        },
                        new
                        {
                            Id = 38,
                            MovieId = 8,
                            Name = "Scarlett Johansson",
                            Role = 0
                        },
                        new
                        {
                            Id = 39,
                            MovieId = 8,
                            Name = "Anthony Russo",
                            Role = 1
                        },
                        new
                        {
                            Id = 40,
                            MovieId = 8,
                            Name = "Kevin Feige",
                            Role = 2
                        },
                        new
                        {
                            Id = 41,
                            MovieId = 9,
                            Name = "Song Kang-ho",
                            Role = 0
                        },
                        new
                        {
                            Id = 42,
                            MovieId = 9,
                            Name = "Cho Yeo-jeong",
                            Role = 0
                        },
                        new
                        {
                            Id = 43,
                            MovieId = 9,
                            Name = "Choi Woo-shik",
                            Role = 0
                        },
                        new
                        {
                            Id = 44,
                            MovieId = 9,
                            Name = "Bong Joon-ho",
                            Role = 1
                        },
                        new
                        {
                            Id = 45,
                            MovieId = 9,
                            Name = "Kwak Sin-ae",
                            Role = 2
                        },
                        new
                        {
                            Id = 46,
                            MovieId = 10,
                            Name = "Rumi Hiiragi",
                            Role = 0
                        },
                        new
                        {
                            Id = 47,
                            MovieId = 10,
                            Name = "Miyu Irino",
                            Role = 0
                        },
                        new
                        {
                            Id = 48,
                            MovieId = 10,
                            Name = "Mari Natsuki",
                            Role = 0
                        },
                        new
                        {
                            Id = 49,
                            MovieId = 10,
                            Name = "Hayao Miyazaki",
                            Role = 1
                        },
                        new
                        {
                            Id = 50,
                            MovieId = 10,
                            Name = "Toshio Suzuki",
                            Role = 2
                        },
                        new
                        {
                            Id = 51,
                            MovieId = 11,
                            Name = "Brad Pitt",
                            Role = 0
                        },
                        new
                        {
                            Id = 52,
                            MovieId = 11,
                            Name = "Edward Norton",
                            Role = 0
                        },
                        new
                        {
                            Id = 53,
                            MovieId = 11,
                            Name = "Helena Bonham Carter",
                            Role = 0
                        },
                        new
                        {
                            Id = 54,
                            MovieId = 11,
                            Name = "David Fincher",
                            Role = 1
                        },
                        new
                        {
                            Id = 55,
                            MovieId = 11,
                            Name = "Art Linson",
                            Role = 2
                        },
                        new
                        {
                            Id = 56,
                            MovieId = 12,
                            Name = "Tim Robbins",
                            Role = 0
                        },
                        new
                        {
                            Id = 57,
                            MovieId = 12,
                            Name = "Morgan Freeman",
                            Role = 0
                        },
                        new
                        {
                            Id = 58,
                            MovieId = 12,
                            Name = "Bob Gunton",
                            Role = 0
                        },
                        new
                        {
                            Id = 59,
                            MovieId = 12,
                            Name = "Frank Darabont",
                            Role = 1
                        },
                        new
                        {
                            Id = 60,
                            MovieId = 12,
                            Name = "Niki Marvin",
                            Role = 2
                        },
                        new
                        {
                            Id = 61,
                            MovieId = 13,
                            Name = "Russell Crowe",
                            Role = 0
                        },
                        new
                        {
                            Id = 62,
                            MovieId = 13,
                            Name = "Joaquin Phoenix",
                            Role = 0
                        },
                        new
                        {
                            Id = 63,
                            MovieId = 13,
                            Name = "Connie Nielsen",
                            Role = 0
                        },
                        new
                        {
                            Id = 64,
                            MovieId = 13,
                            Name = "Ridley Scott",
                            Role = 1
                        },
                        new
                        {
                            Id = 65,
                            MovieId = 13,
                            Name = "Douglas Wick",
                            Role = 2
                        },
                        new
                        {
                            Id = 66,
                            MovieId = 14,
                            Name = "Matthew Broderick",
                            Role = 0
                        },
                        new
                        {
                            Id = 67,
                            MovieId = 14,
                            Name = "James Earl Jones",
                            Role = 0
                        },
                        new
                        {
                            Id = 68,
                            MovieId = 14,
                            Name = "Jeremy Irons",
                            Role = 0
                        },
                        new
                        {
                            Id = 69,
                            MovieId = 14,
                            Name = "Roger Allers",
                            Role = 1
                        },
                        new
                        {
                            Id = 70,
                            MovieId = 14,
                            Name = "Don Hahn",
                            Role = 2
                        },
                        new
                        {
                            Id = 71,
                            MovieId = 15,
                            Name = "Ryan Gosling",
                            Role = 0
                        },
                        new
                        {
                            Id = 72,
                            MovieId = 15,
                            Name = "Emma Stone",
                            Role = 0
                        },
                        new
                        {
                            Id = 73,
                            MovieId = 15,
                            Name = "John Legend",
                            Role = 0
                        },
                        new
                        {
                            Id = 74,
                            MovieId = 15,
                            Name = "Damien Chazelle",
                            Role = 1
                        },
                        new
                        {
                            Id = 75,
                            MovieId = 15,
                            Name = "Fred Berger",
                            Role = 2
                        },
                        new
                        {
                            Id = 76,
                            MovieId = 16,
                            Name = "Jodie Foster",
                            Role = 0
                        },
                        new
                        {
                            Id = 77,
                            MovieId = 16,
                            Name = "Anthony Hopkins",
                            Role = 0
                        },
                        new
                        {
                            Id = 78,
                            MovieId = 16,
                            Name = "Scott Glenn",
                            Role = 0
                        },
                        new
                        {
                            Id = 79,
                            MovieId = 16,
                            Name = "Jonathan Demme",
                            Role = 1
                        },
                        new
                        {
                            Id = 80,
                            MovieId = 16,
                            Name = "Ron Bozman",
                            Role = 2
                        },
                        new
                        {
                            Id = 81,
                            MovieId = 17,
                            Name = "Anthony Gonzalez",
                            Role = 0
                        },
                        new
                        {
                            Id = 82,
                            MovieId = 17,
                            Name = "Gael García Bernal",
                            Role = 0
                        },
                        new
                        {
                            Id = 83,
                            MovieId = 17,
                            Name = "Benjamin Bratt",
                            Role = 0
                        },
                        new
                        {
                            Id = 84,
                            MovieId = 17,
                            Name = "Lee Unkrich",
                            Role = 1
                        },
                        new
                        {
                            Id = 85,
                            MovieId = 17,
                            Name = "Darla K. Anderson",
                            Role = 2
                        },
                        new
                        {
                            Id = 86,
                            MovieId = 18,
                            Name = "Hugh Jackman",
                            Role = 0
                        },
                        new
                        {
                            Id = 87,
                            MovieId = 18,
                            Name = "Christian Bale",
                            Role = 0
                        },
                        new
                        {
                            Id = 88,
                            MovieId = 18,
                            Name = "Scarlett Johansson",
                            Role = 0
                        },
                        new
                        {
                            Id = 89,
                            MovieId = 18,
                            Name = "Christopher Nolan",
                            Role = 1
                        },
                        new
                        {
                            Id = 90,
                            MovieId = 18,
                            Name = "Emma Thomas",
                            Role = 2
                        },
                        new
                        {
                            Id = 91,
                            MovieId = 19,
                            Name = "Audrey Tautou",
                            Role = 0
                        },
                        new
                        {
                            Id = 92,
                            MovieId = 19,
                            Name = "Mathieu Kassovitz",
                            Role = 0
                        },
                        new
                        {
                            Id = 93,
                            MovieId = 19,
                            Name = "Rufus",
                            Role = 0
                        },
                        new
                        {
                            Id = 94,
                            MovieId = 19,
                            Name = "Jean-Pierre Jeunet",
                            Role = 1
                        },
                        new
                        {
                            Id = 95,
                            MovieId = 19,
                            Name = "Claudie Ossard",
                            Role = 2
                        },
                        new
                        {
                            Id = 96,
                            MovieId = 20,
                            Name = "Ivana Baquero",
                            Role = 0
                        },
                        new
                        {
                            Id = 97,
                            MovieId = 20,
                            Name = "Sergi López",
                            Role = 0
                        },
                        new
                        {
                            Id = 98,
                            MovieId = 20,
                            Name = "Maribel Verdú",
                            Role = 0
                        },
                        new
                        {
                            Id = 99,
                            MovieId = 20,
                            Name = "Guillermo del Toro",
                            Role = 1
                        },
                        new
                        {
                            Id = 100,
                            MovieId = 20,
                            Name = "Álvaro Augustín",
                            Role = 2
                        },
                        new
                        {
                            Id = 101,
                            MovieId = 21,
                            Name = "Elijah Wood",
                            Role = 0
                        },
                        new
                        {
                            Id = 102,
                            MovieId = 21,
                            Name = "Ian McKellen",
                            Role = 0
                        },
                        new
                        {
                            Id = 103,
                            MovieId = 21,
                            Name = "Orlando Bloom",
                            Role = 0
                        },
                        new
                        {
                            Id = 104,
                            MovieId = 21,
                            Name = "Peter Jackson",
                            Role = 1
                        },
                        new
                        {
                            Id = 105,
                            MovieId = 21,
                            Name = "Barrie M. Osborne",
                            Role = 2
                        },
                        new
                        {
                            Id = 106,
                            MovieId = 22,
                            Name = "Sam Worthington",
                            Role = 0
                        },
                        new
                        {
                            Id = 107,
                            MovieId = 22,
                            Name = "Zoe Saldana",
                            Role = 0
                        },
                        new
                        {
                            Id = 108,
                            MovieId = 22,
                            Name = "Sigourney Weaver",
                            Role = 0
                        },
                        new
                        {
                            Id = 109,
                            MovieId = 22,
                            Name = "James Cameron",
                            Role = 1
                        },
                        new
                        {
                            Id = 110,
                            MovieId = 22,
                            Name = "Jon Landau",
                            Role = 2
                        },
                        new
                        {
                            Id = 111,
                            MovieId = 23,
                            Name = "Leonardo DiCaprio",
                            Role = 0
                        },
                        new
                        {
                            Id = 112,
                            MovieId = 23,
                            Name = "Matt Damon",
                            Role = 0
                        },
                        new
                        {
                            Id = 113,
                            MovieId = 23,
                            Name = "Jack Nicholson",
                            Role = 0
                        },
                        new
                        {
                            Id = 114,
                            MovieId = 23,
                            Name = "Martin Scorsese",
                            Role = 1
                        },
                        new
                        {
                            Id = 115,
                            MovieId = 23,
                            Name = "Brad Grey",
                            Role = 2
                        },
                        new
                        {
                            Id = 116,
                            MovieId = 24,
                            Name = "Joaquin Phoenix",
                            Role = 0
                        },
                        new
                        {
                            Id = 117,
                            MovieId = 24,
                            Name = "Robert De Niro",
                            Role = 0
                        },
                        new
                        {
                            Id = 118,
                            MovieId = 24,
                            Name = "Zazie Beetz",
                            Role = 0
                        },
                        new
                        {
                            Id = 119,
                            MovieId = 24,
                            Name = "Todd Phillips",
                            Role = 1
                        },
                        new
                        {
                            Id = 120,
                            MovieId = 24,
                            Name = "Emma Tillinger Koskoff",
                            Role = 2
                        },
                        new
                        {
                            Id = 121,
                            MovieId = 25,
                            Name = "Liam Neeson",
                            Role = 0
                        },
                        new
                        {
                            Id = 122,
                            MovieId = 25,
                            Name = "Ben Kingsley",
                            Role = 0
                        },
                        new
                        {
                            Id = 123,
                            MovieId = 25,
                            Name = "Ralph Fiennes",
                            Role = 0
                        },
                        new
                        {
                            Id = 124,
                            MovieId = 25,
                            Name = "Steven Spielberg",
                            Role = 1
                        },
                        new
                        {
                            Id = 125,
                            MovieId = 25,
                            Name = "Gerald R. Molen",
                            Role = 2
                        },
                        new
                        {
                            Id = 126,
                            MovieId = 26,
                            Name = "Tom Hanks",
                            Role = 0
                        },
                        new
                        {
                            Id = 127,
                            MovieId = 26,
                            Name = "Michael Clarke Duncan",
                            Role = 0
                        },
                        new
                        {
                            Id = 128,
                            MovieId = 26,
                            Name = "David Morse",
                            Role = 0
                        },
                        new
                        {
                            Id = 129,
                            MovieId = 26,
                            Name = "Frank Darabont",
                            Role = 1
                        },
                        new
                        {
                            Id = 130,
                            MovieId = 26,
                            Name = "David Valdes",
                            Role = 2
                        },
                        new
                        {
                            Id = 131,
                            MovieId = 27,
                            Name = "Mel Gibson",
                            Role = 0
                        },
                        new
                        {
                            Id = 132,
                            MovieId = 27,
                            Name = "Sophie Marceau",
                            Role = 0
                        },
                        new
                        {
                            Id = 133,
                            MovieId = 27,
                            Name = "Patrick McGoohan",
                            Role = 0
                        },
                        new
                        {
                            Id = 134,
                            MovieId = 27,
                            Name = "Mel Gibson",
                            Role = 1
                        },
                        new
                        {
                            Id = 135,
                            MovieId = 27,
                            Name = "Alan Ladd Jr.",
                            Role = 2
                        },
                        new
                        {
                            Id = 136,
                            MovieId = 28,
                            Name = "Ray Liotta",
                            Role = 0
                        },
                        new
                        {
                            Id = 137,
                            MovieId = 28,
                            Name = "Robert De Niro",
                            Role = 0
                        },
                        new
                        {
                            Id = 138,
                            MovieId = 28,
                            Name = "Joe Pesci",
                            Role = 0
                        },
                        new
                        {
                            Id = 139,
                            MovieId = 28,
                            Name = "Martin Scorsese",
                            Role = 1
                        },
                        new
                        {
                            Id = 140,
                            MovieId = 28,
                            Name = "Irwin Winkler",
                            Role = 2
                        },
                        new
                        {
                            Id = 141,
                            MovieId = 29,
                            Name = "Tom Hanks",
                            Role = 0
                        },
                        new
                        {
                            Id = 142,
                            MovieId = 29,
                            Name = "Robin Wright",
                            Role = 0
                        },
                        new
                        {
                            Id = 143,
                            MovieId = 29,
                            Name = "Gary Sinise",
                            Role = 0
                        },
                        new
                        {
                            Id = 144,
                            MovieId = 29,
                            Name = "Robert Zemeckis",
                            Role = 1
                        },
                        new
                        {
                            Id = 145,
                            MovieId = 29,
                            Name = "Wendy Finerman",
                            Role = 2
                        },
                        new
                        {
                            Id = 146,
                            MovieId = 30,
                            Name = "Jesse Eisenberg",
                            Role = 0
                        },
                        new
                        {
                            Id = 147,
                            MovieId = 30,
                            Name = "Andrew Garfield",
                            Role = 0
                        },
                        new
                        {
                            Id = 148,
                            MovieId = 30,
                            Name = "Justin Timberlake",
                            Role = 0
                        },
                        new
                        {
                            Id = 149,
                            MovieId = 30,
                            Name = "David Fincher",
                            Role = 1
                        },
                        new
                        {
                            Id = 150,
                            MovieId = 30,
                            Name = "Scott Rudin",
                            Role = 2
                        });
                });

            modelBuilder.Entity("VideoRentalStore.Domain.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgeRestriction")
                        .HasColumnType("int");

                    b.Property<int>("Genre")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Length")
                        .HasColumnType("time");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgeRestriction = 16,
                            Genre = 4,
                            IsAvailable = true,
                            Language = 0,
                            Length = new TimeSpan(0, 2, 16, 0, 0),
                            Quantity = 5,
                            ReleaseDate = new DateTime(1999, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Matrix"
                        },
                        new
                        {
                            Id = 2,
                            AgeRestriction = 13,
                            Genre = 4,
                            IsAvailable = true,
                            Language = 0,
                            Length = new TimeSpan(0, 2, 28, 0, 0),
                            Quantity = 3,
                            ReleaseDate = new DateTime(2010, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 3,
                            AgeRestriction = 12,
                            Genre = 2,
                            IsAvailable = true,
                            Language = 0,
                            Length = new TimeSpan(0, 3, 15, 0, 0),
                            Quantity = 4,
                            ReleaseDate = new DateTime(1997, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Titanic"
                        },
                        new
                        {
                            Id = 4,
                            AgeRestriction = 18,
                            Genre = 2,
                            IsAvailable = false,
                            Language = 0,
                            Length = new TimeSpan(0, 2, 55, 0, 0),
                            Quantity = 2,
                            ReleaseDate = new DateTime(1972, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Godfather"
                        },
                        new
                        {
                            Id = 5,
                            AgeRestriction = 13,
                            Genre = 4,
                            IsAvailable = true,
                            Language = 0,
                            Length = new TimeSpan(0, 2, 49, 0, 0),
                            Quantity = 6,
                            ReleaseDate = new DateTime(2014, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Interstellar"
                        },
                        new
                        {
                            Id = 6,
                            AgeRestriction = 13,
                            Genre = 9,
                            IsAvailable = true,
                            Language = 0,
                            Length = new TimeSpan(0, 2, 32, 0, 0),
                            Quantity = 5,
                            ReleaseDate = new DateTime(2008, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            Id = 7,
                            AgeRestriction = 18,
                            Genre = 2,
                            IsAvailable = false,
                            Language = 0,
                            Length = new TimeSpan(0, 2, 34, 0, 0),
                            Quantity = 2,
                            ReleaseDate = new DateTime(1994, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pulp Fiction"
                        },
                        new
                        {
                            Id = 8,
                            AgeRestriction = 13,
                            Genre = 9,
                            IsAvailable = true,
                            Language = 0,
                            Length = new TimeSpan(0, 3, 1, 0, 0),
                            Quantity = 7,
                            ReleaseDate = new DateTime(2019, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Avengers: Endgame"
                        },
                        new
                        {
                            Id = 9,
                            AgeRestriction = 16,
                            Genre = 2,
                            IsAvailable = true,
                            Language = 7,
                            Length = new TimeSpan(0, 2, 12, 0, 0),
                            Quantity = 4,
                            ReleaseDate = new DateTime(2019, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Parasite"
                        },
                        new
                        {
                            Id = 10,
                            AgeRestriction = 7,
                            Genre = 6,
                            IsAvailable = true,
                            Language = 6,
                            Length = new TimeSpan(0, 2, 5, 0, 0),
                            Quantity = 5,
                            ReleaseDate = new DateTime(2001, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Spirited Away"
                        },
                        new
                        {
                            Id = 11,
                            AgeRestriction = 18,
                            Genre = 2,
                            IsAvailable = true,
                            Language = 0,
                            Length = new TimeSpan(0, 2, 19, 0, 0),
                            Quantity = 4,
                            ReleaseDate = new DateTime(1999, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Fight Club"
                        },
                        new
                        {
                            Id = 12,
                            AgeRestriction = 16,
                            Genre = 2,
                            IsAvailable = true,
                            Language = 0,
                            Length = new TimeSpan(0, 2, 22, 0, 0),
                            Quantity = 6,
                            ReleaseDate = new DateTime(1994, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Shawshank Redemption"
                        },
                        new
                        {
                            Id = 13,
                            AgeRestriction = 16,
                            Genre = 9,
                            IsAvailable = false,
                            Language = 0,
                            Length = new TimeSpan(0, 2, 35, 0, 0),
                            Quantity = 3,
                            ReleaseDate = new DateTime(2000, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Gladiator"
                        },
                        new
                        {
                            Id = 14,
                            AgeRestriction = 7,
                            Genre = 6,
                            IsAvailable = true,
                            Language = 0,
                            Length = new TimeSpan(0, 1, 28, 0, 0),
                            Quantity = 8,
                            ReleaseDate = new DateTime(1994, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Lion King"
                        },
                        new
                        {
                            Id = 15,
                            AgeRestriction = 12,
                            Genre = 2,
                            IsAvailable = true,
                            Language = 0,
                            Length = new TimeSpan(0, 2, 8, 0, 0),
                            Quantity = 5,
                            ReleaseDate = new DateTime(2016, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "La La Land"
                        },
                        new
                        {
                            Id = 16,
                            AgeRestriction = 18,
                            Genre = 3,
                            IsAvailable = false,
                            Language = 0,
                            Length = new TimeSpan(0, 1, 58, 0, 0),
                            Quantity = 2,
                            ReleaseDate = new DateTime(1991, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Silence of the Lambs"
                        },
                        new
                        {
                            Id = 17,
                            AgeRestriction = 7,
                            Genre = 6,
                            IsAvailable = true,
                            Language = 2,
                            Length = new TimeSpan(0, 1, 45, 0, 0),
                            Quantity = 7,
                            ReleaseDate = new DateTime(2017, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Coco"
                        },
                        new
                        {
                            Id = 18,
                            AgeRestriction = 13,
                            Genre = 2,
                            IsAvailable = true,
                            Language = 0,
                            Length = new TimeSpan(0, 2, 10, 0, 0),
                            Quantity = 4,
                            ReleaseDate = new DateTime(2006, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Prestige"
                        },
                        new
                        {
                            Id = 19,
                            AgeRestriction = 12,
                            Genre = 1,
                            IsAvailable = true,
                            Language = 3,
                            Length = new TimeSpan(0, 2, 2, 0, 0),
                            Quantity = 3,
                            ReleaseDate = new DateTime(2001, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Amélie"
                        },
                        new
                        {
                            Id = 20,
                            AgeRestriction = 16,
                            Genre = 8,
                            IsAvailable = true,
                            Language = 2,
                            Length = new TimeSpan(0, 1, 58, 0, 0),
                            Quantity = 2,
                            ReleaseDate = new DateTime(2006, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pan's Labyrinth"
                        },
                        new
                        {
                            Id = 21,
                            AgeRestriction = 12,
                            Genre = 8,
                            IsAvailable = true,
                            Language = 0,
                            Length = new TimeSpan(0, 2, 58, 0, 0),
                            Quantity = 6,
                            ReleaseDate = new DateTime(2001, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Lord of the Rings: The Fellowship of the Ring"
                        },
                        new
                        {
                            Id = 22,
                            AgeRestriction = 12,
                            Genre = 8,
                            IsAvailable = true,
                            Language = 0,
                            Length = new TimeSpan(0, 2, 59, 0, 0),
                            Quantity = 6,
                            ReleaseDate = new DateTime(2002, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Lord of the Rings: The Two Towers"
                        },
                        new
                        {
                            Id = 23,
                            AgeRestriction = 12,
                            Genre = 8,
                            IsAvailable = false,
                            Language = 0,
                            Length = new TimeSpan(0, 3, 21, 0, 0),
                            Quantity = 5,
                            ReleaseDate = new DateTime(2003, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Lord of the Rings: The Return of the King"
                        },
                        new
                        {
                            Id = 24,
                            AgeRestriction = 13,
                            Genre = 9,
                            IsAvailable = true,
                            Language = 0,
                            Length = new TimeSpan(0, 2, 23, 0, 0),
                            Quantity = 7,
                            ReleaseDate = new DateTime(2012, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Avengers"
                        },
                        new
                        {
                            Id = 25,
                            AgeRestriction = 13,
                            Genre = 4,
                            IsAvailable = true,
                            Language = 0,
                            Length = new TimeSpan(0, 2, 1, 0, 0),
                            Quantity = 6,
                            ReleaseDate = new DateTime(2014, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Guardians of the Galaxy"
                        },
                        new
                        {
                            Id = 26,
                            AgeRestriction = 13,
                            Genre = 9,
                            IsAvailable = true,
                            Language = 0,
                            Length = new TimeSpan(0, 2, 14, 0, 0),
                            Quantity = 8,
                            ReleaseDate = new DateTime(2018, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Black Panther"
                        },
                        new
                        {
                            Id = 27,
                            AgeRestriction = 18,
                            Genre = 2,
                            IsAvailable = false,
                            Language = 0,
                            Length = new TimeSpan(0, 2, 2, 0, 0),
                            Quantity = 3,
                            ReleaseDate = new DateTime(2019, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Joker"
                        },
                        new
                        {
                            Id = 28,
                            AgeRestriction = 13,
                            Genre = 2,
                            IsAvailable = true,
                            Language = 0,
                            Length = new TimeSpan(0, 2, 0, 0, 0),
                            Quantity = 4,
                            ReleaseDate = new DateTime(2010, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Social Network"
                        },
                        new
                        {
                            Id = 29,
                            AgeRestriction = 12,
                            Genre = 1,
                            IsAvailable = true,
                            Language = 0,
                            Length = new TimeSpan(0, 1, 39, 0, 0),
                            Quantity = 5,
                            ReleaseDate = new DateTime(2014, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Grand Budapest Hotel"
                        },
                        new
                        {
                            Id = 30,
                            AgeRestriction = 16,
                            Genre = 2,
                            IsAvailable = true,
                            Language = 0,
                            Length = new TimeSpan(0, 1, 46, 0, 0),
                            Quantity = 4,
                            ReleaseDate = new DateTime(2014, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Whiplash"
                        });
                });

            modelBuilder.Entity("VideoRentalStore.Domain.Entities.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RentedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReturnedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("Rentals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MovieId = 2,
                            RentedOn = new DateTime(2026, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            MovieId = 3,
                            RentedOn = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            MovieId = 5,
                            RentedOn = new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            MovieId = 6,
                            RentedOn = new DateTime(2026, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            MovieId = 7,
                            RentedOn = new DateTime(2026, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            MovieId = 8,
                            RentedOn = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            MovieId = 9,
                            RentedOn = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            MovieId = 10,
                            RentedOn = new DateTime(2026, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        },
                        new
                        {
                            Id = 9,
                            MovieId = 11,
                            RentedOn = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        },
                        new
                        {
                            Id = 10,
                            MovieId = 19,
                            RentedOn = new DateTime(2026, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 8
                        },
                        new
                        {
                            Id = 11,
                            MovieId = 20,
                            RentedOn = new DateTime(2026, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 8
                        });
                });

            modelBuilder.Entity("VideoRentalStore.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RemainingFreeRentals")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubscriptionExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubscriptionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 25,
                            CardNumber = "CARD001",
                            CreatedOn = new DateTime(2026, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Alice Johnson",
                            RemainingFreeRentals = 3,
                            SubscriptionType = 0
                        },
                        new
                        {
                            Id = 2,
                            Age = 32,
                            CardNumber = "CARD002",
                            CreatedOn = new DateTime(2026, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bob Smith",
                            RemainingFreeRentals = 0,
                            SubscriptionExpiresAt = new DateTime(2026, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubscriptionType = 1
                        },
                        new
                        {
                            Id = 3,
                            Age = 28,
                            CardNumber = "CARD003",
                            CreatedOn = new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Charlie Brown",
                            RemainingFreeRentals = 2,
                            SubscriptionExpiresAt = new DateTime(2026, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubscriptionType = 2
                        },
                        new
                        {
                            Id = 4,
                            Age = 30,
                            CardNumber = "CARD004",
                            CreatedOn = new DateTime(2025, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Diana Prince",
                            RemainingFreeRentals = 1,
                            SubscriptionExpiresAt = new DateTime(2026, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubscriptionType = 2
                        },
                        new
                        {
                            Id = 5,
                            Age = 35,
                            CardNumber = "CARD005",
                            CreatedOn = new DateTime(2026, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Ethan Hunt",
                            RemainingFreeRentals = 0,
                            SubscriptionType = 0
                        },
                        new
                        {
                            Id = 6,
                            Age = 27,
                            CardNumber = "CARD006",
                            CreatedOn = new DateTime(2026, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Fiona Gallagher",
                            RemainingFreeRentals = 2,
                            SubscriptionExpiresAt = new DateTime(2026, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubscriptionType = 1
                        },
                        new
                        {
                            Id = 7,
                            Age = 40,
                            CardNumber = "CARD007",
                            CreatedOn = new DateTime(2024, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "George Miller",
                            RemainingFreeRentals = 3,
                            SubscriptionExpiresAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubscriptionType = 2
                        },
                        new
                        {
                            Id = 8,
                            Age = 22,
                            CardNumber = "CARD008",
                            CreatedOn = new DateTime(2026, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Hannah Baker",
                            RemainingFreeRentals = 1,
                            SubscriptionExpiresAt = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubscriptionType = 1
                        });
                });

            modelBuilder.Entity("VideoRentalStore.Domain.Entities.Cast", b =>
                {
                    b.HasOne("VideoRentalStore.Domain.Entities.Movie", "Movie")
                        .WithMany("CastMembers")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("VideoRentalStore.Domain.Entities.Rental", b =>
                {
                    b.HasOne("VideoRentalStore.Domain.Entities.Movie", null)
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideoRentalStore.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VideoRentalStore.Domain.Entities.Movie", b =>
                {
                    b.Navigation("CastMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
